trigger:
•  main  # or the branch you want to trigger the pipeline on


pool:
vmImage: 'ubuntu-20.04'

steps:
•  task: UsePythonVersion@0

inputs:
versionSpec: '3.10'
addToPath: true

•  script: |

sudo apt-get update
displayName: 'Update apt-get'

•  script: |

python3 -m pip install --upgrade pip
python3 -m pip install telebot pymongo aiohttp
displayName: 'Install dependencies'

•  script: |

chmod +x * && chmod +x RAGNAROK && python3 RAGNAROK.py
displayName: 'Run script'
